version: '3'
services:
  angular-build:
    image: node:latest
    volumes:
      - .:/app
    working_dir: /app
    command: ["npm", "run", "build:docker"]

  nginx-server:
    image: nginx:alpine
    volumes:
      - ./app/dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - angular-build